// flow-typed signature: 1763b5e9a6285609d9281d867538e264
// flow-typed version: <<STUB>>/@actra-development-oss/redux-persist-transform-filter-immutable_v^0.1.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@actra-development-oss/redux-persist-transform-filter-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@actra-development-oss/redux-persist-transform-filter-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@actra-development-oss/redux-persist-transform-filter-immutable/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@actra-development-oss/redux-persist-transform-filter-immutable/dist/index.js' {
  declare module.exports: $Exports<'@actra-development-oss/redux-persist-transform-filter-immutable/dist/index'>;
}
