// flow-typed signature: 8308b0831bd6189274c068e4bf6939d8
// flow-typed version: <<STUB>>/art_v^0.10.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'art'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'art' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'art/core/class' {
  declare module.exports: any;
}

declare module 'art/core/color' {
  declare module.exports: any;
}

declare module 'art/core/path' {
  declare module.exports: any;
}

declare module 'art/core/transform' {
  declare module.exports: any;
}

declare module 'art/dom/container' {
  declare module.exports: any;
}

declare module 'art/dom/dummy' {
  declare module.exports: any;
}

declare module 'art/dom/native' {
  declare module.exports: any;
}

declare module 'art/dom/shadow' {
  declare module.exports: any;
}

declare module 'art/lib/Sheet.Cascade' {
  declare module.exports: any;
}

declare module 'art/metrics/path' {
  declare module.exports: any;
}

declare module 'art/modes/canvas' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/_image' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/base' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/clippingrectangle' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/group' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/node' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/path' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/shape' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/surface' {
  declare module.exports: any;
}

declare module 'art/modes/canvas/text' {
  declare module.exports: any;
}

declare module 'art/modes/current' {
  declare module.exports: any;
}

declare module 'art/modes/dom' {
  declare module.exports: any;
}

declare module 'art/modes/fast-noSideEffects' {
  declare module.exports: any;
}

declare module 'art/modes/fast' {
  declare module.exports: any;
}

declare module 'art/modes/script' {
  declare module.exports: any;
}

declare module 'art/modes/script/_image' {
  declare module.exports: any;
}

declare module 'art/modes/script/base' {
  declare module.exports: any;
}

declare module 'art/modes/script/font' {
  declare module.exports: any;
}

declare module 'art/modes/script/group' {
  declare module.exports: any;
}

declare module 'art/modes/script/modulizer' {
  declare module.exports: any;
}

declare module 'art/modes/script/node' {
  declare module.exports: any;
}

declare module 'art/modes/script/path' {
  declare module.exports: any;
}

declare module 'art/modes/script/shape' {
  declare module.exports: any;
}

declare module 'art/modes/script/surface' {
  declare module.exports: any;
}

declare module 'art/modes/script/text' {
  declare module.exports: any;
}

declare module 'art/modes/svg' {
  declare module.exports: any;
}

declare module 'art/modes/svg/_image' {
  declare module.exports: any;
}

declare module 'art/modes/svg/base' {
  declare module.exports: any;
}

declare module 'art/modes/svg/dom' {
  declare module.exports: any;
}

declare module 'art/modes/svg/group' {
  declare module.exports: any;
}

declare module 'art/modes/svg/node' {
  declare module.exports: any;
}

declare module 'art/modes/svg/path' {
  declare module.exports: any;
}

declare module 'art/modes/svg/shape' {
  declare module.exports: any;
}

declare module 'art/modes/svg/surface' {
  declare module.exports: any;
}

declare module 'art/modes/svg/text' {
  declare module.exports: any;
}

declare module 'art/modes/vml' {
  declare module.exports: any;
}

declare module 'art/modes/vml/base' {
  declare module.exports: any;
}

declare module 'art/modes/vml/clippingrectangle' {
  declare module.exports: any;
}

declare module 'art/modes/vml/dom' {
  declare module.exports: any;
}

declare module 'art/modes/vml/group' {
  declare module.exports: any;
}

declare module 'art/modes/vml/node' {
  declare module.exports: any;
}

declare module 'art/modes/vml/path' {
  declare module.exports: any;
}

declare module 'art/modes/vml/shape' {
  declare module.exports: any;
}

declare module 'art/modes/vml/surface' {
  declare module.exports: any;
}

declare module 'art/modes/vml/text' {
  declare module.exports: any;
}

declare module 'art/morph/path' {
  declare module.exports: any;
}

declare module 'art/parsers/svg' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/colors' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/core' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/externals' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/fonts' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/markers' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/paints' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/shapes' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/styles' {
  declare module.exports: any;
}

declare module 'art/parsers/svg/text' {
  declare module.exports: any;
}

declare module 'art/shapes/ellipse' {
  declare module.exports: any;
}

declare module 'art/shapes/font' {
  declare module.exports: any;
}

declare module 'art/shapes/generic' {
  declare module.exports: any;
}

declare module 'art/shapes/pill' {
  declare module.exports: any;
}

declare module 'art/shapes/rectangle' {
  declare module.exports: any;
}

declare module 'art/shapes/wedge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'art/core/class.js' {
  declare module.exports: $Exports<'art/core/class'>;
}
declare module 'art/core/color.js' {
  declare module.exports: $Exports<'art/core/color'>;
}
declare module 'art/core/path.js' {
  declare module.exports: $Exports<'art/core/path'>;
}
declare module 'art/core/transform.js' {
  declare module.exports: $Exports<'art/core/transform'>;
}
declare module 'art/dom/container.js' {
  declare module.exports: $Exports<'art/dom/container'>;
}
declare module 'art/dom/dummy.js' {
  declare module.exports: $Exports<'art/dom/dummy'>;
}
declare module 'art/dom/native.js' {
  declare module.exports: $Exports<'art/dom/native'>;
}
declare module 'art/dom/shadow.js' {
  declare module.exports: $Exports<'art/dom/shadow'>;
}
declare module 'art/index' {
  declare module.exports: $Exports<'art'>;
}
declare module 'art/index.js' {
  declare module.exports: $Exports<'art'>;
}
declare module 'art/lib/Sheet.Cascade.js' {
  declare module.exports: $Exports<'art/lib/Sheet.Cascade'>;
}
declare module 'art/metrics/path.js' {
  declare module.exports: $Exports<'art/metrics/path'>;
}
declare module 'art/modes/canvas.js' {
  declare module.exports: $Exports<'art/modes/canvas'>;
}
declare module 'art/modes/canvas/_image.js' {
  declare module.exports: $Exports<'art/modes/canvas/_image'>;
}
declare module 'art/modes/canvas/base.js' {
  declare module.exports: $Exports<'art/modes/canvas/base'>;
}
declare module 'art/modes/canvas/clippingrectangle.js' {
  declare module.exports: $Exports<'art/modes/canvas/clippingrectangle'>;
}
declare module 'art/modes/canvas/group.js' {
  declare module.exports: $Exports<'art/modes/canvas/group'>;
}
declare module 'art/modes/canvas/node.js' {
  declare module.exports: $Exports<'art/modes/canvas/node'>;
}
declare module 'art/modes/canvas/path.js' {
  declare module.exports: $Exports<'art/modes/canvas/path'>;
}
declare module 'art/modes/canvas/shape.js' {
  declare module.exports: $Exports<'art/modes/canvas/shape'>;
}
declare module 'art/modes/canvas/surface.js' {
  declare module.exports: $Exports<'art/modes/canvas/surface'>;
}
declare module 'art/modes/canvas/text.js' {
  declare module.exports: $Exports<'art/modes/canvas/text'>;
}
declare module 'art/modes/current.js' {
  declare module.exports: $Exports<'art/modes/current'>;
}
declare module 'art/modes/dom.js' {
  declare module.exports: $Exports<'art/modes/dom'>;
}
declare module 'art/modes/fast-noSideEffects.js' {
  declare module.exports: $Exports<'art/modes/fast-noSideEffects'>;
}
declare module 'art/modes/fast.js' {
  declare module.exports: $Exports<'art/modes/fast'>;
}
declare module 'art/modes/script.js' {
  declare module.exports: $Exports<'art/modes/script'>;
}
declare module 'art/modes/script/_image.js' {
  declare module.exports: $Exports<'art/modes/script/_image'>;
}
declare module 'art/modes/script/base.js' {
  declare module.exports: $Exports<'art/modes/script/base'>;
}
declare module 'art/modes/script/font.js' {
  declare module.exports: $Exports<'art/modes/script/font'>;
}
declare module 'art/modes/script/group.js' {
  declare module.exports: $Exports<'art/modes/script/group'>;
}
declare module 'art/modes/script/modulizer.js' {
  declare module.exports: $Exports<'art/modes/script/modulizer'>;
}
declare module 'art/modes/script/node.js' {
  declare module.exports: $Exports<'art/modes/script/node'>;
}
declare module 'art/modes/script/path.js' {
  declare module.exports: $Exports<'art/modes/script/path'>;
}
declare module 'art/modes/script/shape.js' {
  declare module.exports: $Exports<'art/modes/script/shape'>;
}
declare module 'art/modes/script/surface.js' {
  declare module.exports: $Exports<'art/modes/script/surface'>;
}
declare module 'art/modes/script/text.js' {
  declare module.exports: $Exports<'art/modes/script/text'>;
}
declare module 'art/modes/svg.js' {
  declare module.exports: $Exports<'art/modes/svg'>;
}
declare module 'art/modes/svg/_image.js' {
  declare module.exports: $Exports<'art/modes/svg/_image'>;
}
declare module 'art/modes/svg/base.js' {
  declare module.exports: $Exports<'art/modes/svg/base'>;
}
declare module 'art/modes/svg/dom.js' {
  declare module.exports: $Exports<'art/modes/svg/dom'>;
}
declare module 'art/modes/svg/group.js' {
  declare module.exports: $Exports<'art/modes/svg/group'>;
}
declare module 'art/modes/svg/node.js' {
  declare module.exports: $Exports<'art/modes/svg/node'>;
}
declare module 'art/modes/svg/path.js' {
  declare module.exports: $Exports<'art/modes/svg/path'>;
}
declare module 'art/modes/svg/shape.js' {
  declare module.exports: $Exports<'art/modes/svg/shape'>;
}
declare module 'art/modes/svg/surface.js' {
  declare module.exports: $Exports<'art/modes/svg/surface'>;
}
declare module 'art/modes/svg/text.js' {
  declare module.exports: $Exports<'art/modes/svg/text'>;
}
declare module 'art/modes/vml.js' {
  declare module.exports: $Exports<'art/modes/vml'>;
}
declare module 'art/modes/vml/base.js' {
  declare module.exports: $Exports<'art/modes/vml/base'>;
}
declare module 'art/modes/vml/clippingrectangle.js' {
  declare module.exports: $Exports<'art/modes/vml/clippingrectangle'>;
}
declare module 'art/modes/vml/dom.js' {
  declare module.exports: $Exports<'art/modes/vml/dom'>;
}
declare module 'art/modes/vml/group.js' {
  declare module.exports: $Exports<'art/modes/vml/group'>;
}
declare module 'art/modes/vml/node.js' {
  declare module.exports: $Exports<'art/modes/vml/node'>;
}
declare module 'art/modes/vml/path.js' {
  declare module.exports: $Exports<'art/modes/vml/path'>;
}
declare module 'art/modes/vml/shape.js' {
  declare module.exports: $Exports<'art/modes/vml/shape'>;
}
declare module 'art/modes/vml/surface.js' {
  declare module.exports: $Exports<'art/modes/vml/surface'>;
}
declare module 'art/modes/vml/text.js' {
  declare module.exports: $Exports<'art/modes/vml/text'>;
}
declare module 'art/morph/path.js' {
  declare module.exports: $Exports<'art/morph/path'>;
}
declare module 'art/parsers/svg.js' {
  declare module.exports: $Exports<'art/parsers/svg'>;
}
declare module 'art/parsers/svg/colors.js' {
  declare module.exports: $Exports<'art/parsers/svg/colors'>;
}
declare module 'art/parsers/svg/core.js' {
  declare module.exports: $Exports<'art/parsers/svg/core'>;
}
declare module 'art/parsers/svg/externals.js' {
  declare module.exports: $Exports<'art/parsers/svg/externals'>;
}
declare module 'art/parsers/svg/fonts.js' {
  declare module.exports: $Exports<'art/parsers/svg/fonts'>;
}
declare module 'art/parsers/svg/markers.js' {
  declare module.exports: $Exports<'art/parsers/svg/markers'>;
}
declare module 'art/parsers/svg/paints.js' {
  declare module.exports: $Exports<'art/parsers/svg/paints'>;
}
declare module 'art/parsers/svg/shapes.js' {
  declare module.exports: $Exports<'art/parsers/svg/shapes'>;
}
declare module 'art/parsers/svg/styles.js' {
  declare module.exports: $Exports<'art/parsers/svg/styles'>;
}
declare module 'art/parsers/svg/text.js' {
  declare module.exports: $Exports<'art/parsers/svg/text'>;
}
declare module 'art/shapes/ellipse.js' {
  declare module.exports: $Exports<'art/shapes/ellipse'>;
}
declare module 'art/shapes/font.js' {
  declare module.exports: $Exports<'art/shapes/font'>;
}
declare module 'art/shapes/generic.js' {
  declare module.exports: $Exports<'art/shapes/generic'>;
}
declare module 'art/shapes/pill.js' {
  declare module.exports: $Exports<'art/shapes/pill'>;
}
declare module 'art/shapes/rectangle.js' {
  declare module.exports: $Exports<'art/shapes/rectangle'>;
}
declare module 'art/shapes/wedge.js' {
  declare module.exports: $Exports<'art/shapes/wedge'>;
}
