service: crypto

provider:
  name: aws
  runtime: nodejs6.10

stage: staging
region: us-east-1

plugins:
  - serverless-offline
  - serverless-plugin-graphiql

custom:
  serverless-offline:
    babelOptions:
      presets: ["env"]
  handlersDir:
    handlers

functions:
  graphql:
    handler: ${self:custom.handlersDir}/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
